# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
              
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --runtime win-x64

    - name : Organize dist directory
      id: vars
      run: |
        mkdir "dist"
        cp -r blobs/eSpeak-ng/* dist
        cp -r bin/Debug/netstandard2.1/win-x64/tongue.dll dist
        cp -r README.md dist
        cp -r LICENSE dist
        cp -r CHANGELOG.md dist
        echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

    - name: Upload dist directory as artifact
      uses: actions/upload-artifact@v4
      with:
        name: sane-Tongue-${{ steps.vars.outputs.short_sha }}
        path: dist/
        compression-level: 9
        

    
